-- if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- You can also add or configure plugins by creating files in this `plugins/` folder
-- PLEASE REMOVE THE EXAMPLES YOU HAVE NO INTEREST IN BEFORE ENABLING THIS FILE
-- Here are some examples:

---@type LazySpec
return {

  -- == Examples of Adding Plugins ==

  "andweeb/presence.nvim",
  {
    "ray-x/lsp_signature.nvim",
    event = "BufRead",
    config = function() require("lsp_signature").setup() end,
  },

  -- == Examples of Overriding Plugins ==

  -- customize dashboard options
  {
    "folke/snacks.nvim",
    opts = {
      dashboard = {
        preset = {
          header = table.concat({
            " █████  ███████ ████████ ██████   ██████ ",
            "██   ██ ██         ██    ██   ██ ██    ██",
            "███████ ███████    ██    ██████  ██    ██",
            "██   ██      ██    ██    ██   ██ ██    ██",
            "██   ██ ███████    ██    ██   ██  ██████ ",
            "",
            "███    ██ ██    ██ ██ ███    ███",
            "████   ██ ██    ██ ██ ████  ████",
            "██ ██  ██ ██    ██ ██ ██ ████ ██",
            "██  ██ ██  ██  ██  ██ ██  ██  ██",
            "██   ████   ████   ██ ██      ██",
          }, "\n"),
        },
      },
      picker = {
        enabled = true,
        ui_select = true;
        sources = {
          files = {
            hidden = true,
            ignored = true,
            exclude = {
              ".git",
              ".vscode",
              "node_modules",
              ".cache",
              "dist",
              "connectedhomeip",
              "build",
              "build-*",
              "build_overrides",
              "out-*",
              "zcl-autogenerated-cluster-config",
            },
          }
        },
        grep = {
          regex = true,
        }
      },
    },
    keys = {
      {
        "<leader>e",
        desc = "Open explorer",
        function()
          require("snacks").picker.explorer()
        end,
      },
      --lsp.preview
      {
        "gpd",
        mode = { "n" },
        function()
          require("snacks").picker.lsp_definitions()
        end,
        desc = "Goto Preview Definition",
      },
      {
        "gpt",
        mode = { "n" },
        function()
          require("snacks").picker.lsp_type_definitions()
        end,
        desc = "Goto Preview Type Definition",
      },
      {
        "gpi",
        mode = { "n" },
        function()
          require("snacks").picker.lsp_implementations()
        end,
        desc = "Goto Preview Implementation",
      },
      {
        "gpD",
        mode = { "n" },
        function()
          require("snacks").picker.lsp_declarations()
        end,
        desc = "Goto Preview Declaration",
      },
      {
        "gpr",
        mode = { "n" },
        function()
          require("snacks").picker.lsp_references()
        end,
        desc = "Goto Preview References",
      },
    }
  },

  { "nvim-neo-tree/nvim-neo-tree", enabled = false }, -- disable by default

  -- You can disable default plugins as follows:
  { "max397574/better-escape.nvim", enabled = true },

  -- You can also easily customize additional setup of plugins that is outside of the plugin's setup call
  {
    "L3MON4D3/LuaSnip",
    config = function(plugin, opts)
      require "astronvim.plugins.configs.luasnip"(plugin, opts) -- include the default astronvim config that calls the setup call
      -- add more custom luasnip configuration such as filetype extend or custom snippets
      local luasnip = require "luasnip"
      luasnip.filetype_extend("javascript", { "javascriptreact" })
    end,
  },

  {
    "windwp/nvim-autopairs",
    config = function(plugin, opts)
      require "astronvim.plugins.configs.nvim-autopairs"(plugin, opts) -- include the default astronvim config that calls the setup call
      -- add more custom autopairs configuration such as custom rules
      local npairs = require "nvim-autopairs"
      local Rule = require "nvim-autopairs.rule"
      local cond = require "nvim-autopairs.conds"
      npairs.add_rules(
        {
          Rule("$", "$", { "tex", "latex" })
            -- don't add a pair if the next character is %
            :with_pair(cond.not_after_regex "%%")
            -- don't add a pair if  the previous character is xxx
            :with_pair(
              cond.not_before_regex("xxx", 3)
            )
            -- don't move right when repeat character
            :with_move(cond.none())
            -- don't delete if the next character is xx
            :with_del(cond.not_after_regex "xx")
            -- disable adding a newline when you press <cr>
            :with_cr(cond.none()),
        },
        -- disable for .vim files, but it work for another filetypes
        Rule("a", "a", "-vim")
      )
    end,
  },

  -- == User added plugins ==
  {
    "okuuva/auto-save.nvim",
    cmd = "ASToggle", -- optional for lazy loading on command
    event = { "InsertLeave" }, -- optional for lazy loading on trigger events
    keys = {
      { "<leader>N", ":ASToggle<CR>", desc = "Toggle auto-save" },
    },
    opts = {
      -- your config goes here
      -- or just leave it empty :)
    },
  },

  {
    "lambdalisue/suda.vim",
    lazy = true,
    keys = {
      { "<leader>W", ":SudaWrite<CR>", desc = "Write with sudo" },
      { "<leader>R", ":SudaRead<CR>", desc = "Read with sudo" },
    },
  },

  {
    "karb94/neoscroll.nvim",
    enabled = false, -- disable by default
    config = function() require("neoscroll").setup {} end,
  },

  {
    "m4xshen/hardtime.nvim",
    enabled = false, -- disable by default
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
    config = function() require("hardtime").setup() end,
  },

  {
    "folke/noice.nvim",
    event = "VeryLazy",
    config = function()
      require("noice").setup {
        -- your noice config goes here
        lsp = {
          signature = { enabled = false },
          hover = { enabled = false },
        },
      }
    end,
    opts = {
      -- add any options here
    },
    dependencies = {
      -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
      "MunifTanjim/nui.nvim",
      -- OPTIONAL:
      --   `nvim-notify` is only needed, if you want to use the notification view.
      --   If not available, we use `mini` as the fallback
      "rcarriga/nvim-notify",
    }
  },

  {
    "mikavilpas/yazi.nvim",
    event = "VeryLazy",
    keys = {
      -- 👇 in this section, choose your own keymappings!
      {
        "<leader>-",
        "<cmd>Yazi<cr>",
        desc = "Open yazi at the current file",
      },
      {
        -- Open in the current working directory
        "<leader>cw",
        "<cmd>Yazi cwd<cr>",
        desc = "Open the file manager in nvim's working directory",
      },
      {
        -- NOTE: this requires a version of yazi that includes
        -- https://github.com/sxyazi/yazi/pull/1305 from 2024-07-18
        "<c-up>",
        "<cmd>Yazi toggle<cr>",
        desc = "Resume the last yazi session",
      },
    },
    opts = {
      -- if you want to open yazi instead of netrw, see below for more info
      open_for_directories = false,
      keymaps = {
        show_help = "<f1>",
      },
      ---@diagnostic disable-next-line: missing-fields
      hooks = {
        ---@diagnostic disable-next-line: unused-local
        yazi_opened = function(_preselected_path, buffer, _config) vim.cmd "set timeoutlen=0" end,
        ---@diagnostic disable-next-line: unused-local
        yazi_closed_successfully = function(_preselected_path, _buffer, _config) vim.cmd "set timeoutlen=500" end,
      },
    },
  },

  {
    "JuanZoran/Trans.nvim",
    build = function() require("Trans").install() end,
    keys = {
      -- you can add keybindings here
      { "mm", mode = { "n", "x" }, "<Cmd>Translate<CR>", desc = "󰊿 Translate" },
      { "mk", mode = { "n", "x" }, "<Cmd>TransPlay<CR>", desc = " Auto Play" },
      -- At present, the window of this function is not ready, you can change the view.i to hover in the configuration
      { "mi", "<Cmd>TranslateInput<CR>", desc = "󰊿 Translate From Input" },
    },
    dependencies = { "kkharji/sqlite.lua" },
    opts = {
      -- your configuration there
    },
  },

  {
    "MeanderingProgrammer/render-markdown.nvim",
    opts = {},
    dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
    -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
  },

  {
    "ggandor/leap.nvim",
    opts = {
      equivalence_classes = { " \t\r\n", "([{", ")]}", "'\"`" },
    },
    dependencies = { "tpope/vim-repeat" },
    keys = {
      { "f", mode = { "n" }, "<Plug>(leap)" },
      { "F", mode = { "n" }, "<Plug>(leap-from-window)" },
      { "f", mode = { "x", "o" }, "<Plug>(leap-forward)" },
      { "F", mode = { "x", "o" }, "<Plug>(leap-backward)" },
    },
  },

  -- {
  --   "folke/flash.nvim",
  --   event = "VeryLazy",
  --   ---@type Flash.Config
  --   opts = {},
  --   -- stylua: ignore
  --   modes = {
  --     char = {
  --       jump_labels = true
  --     }
  --   },
  --   keys = {
  --     { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
  --     { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
  --     { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
  --     { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
  --     { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
  --   },
  -- },

  {
    "sindrets/diffview.nvim",
    enabled = false,
    event = "BufEnter",
    keys = {
      { "<leader>gL", mode = { "n" }, "<Cmd>DiffviewFileHistory<CR>", desc = "Open DiffView File History" },
    },
  },

  -------------------------------------
  ------------- AI plugins ------------
  -------------------------------------

  {
    "greggh/claude-code.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim", -- Required for git operations
    },
    config = function()
      require("claude-code").setup()
    end
  },

  {
    "copilotlsp-nvim/copilot-lsp",
    init = function()
      vim.g.copilot_nes_debounce = 500
      vim.lsp.enable("copilot_ls")
      vim.keymap.set("n", "<tab>", function()
        local bufnr = vim.api.nvim_get_current_buf()
        local state = vim.b[bufnr].nes_state
        if state then
          -- Try to jump to the start of the suggestion edit.
          -- If already at the start, then apply the pending suggestion and jump to the end of the edit.
          local _ = require("copilot-lsp.nes").walk_cursor_start_edit()
            or (
              require("copilot-lsp.nes").apply_pending_nes()
              and require("copilot-lsp.nes").walk_cursor_end_edit()
            )
          return nil
        else
          -- Resolving the terminal's inability to distinguish between `TAB` and `<C-i>` in normal mode
          return "<C-i>"
        end
      end, { desc = "Accept Copilot NES suggestion", expr = true })
    end,
  },

  {
    "zbirenbaum/copilot.lua",
    requires = {
      "copilotlsp-nvim/copilot-lsp",
      init = function()
        vim.g.copilot_nes_debounce = 500
      end,
    },
    cmd = "Copilot",
    event = "InsertEnter",
    config = function()
      require("copilot").setup({
        -- Prevent interference with cmp
        suggestion = { enabled = false },
        panel = { enabled = false },

        -- Enable NES(next edit suggestion) features
        nes = {
          enabled = true,
          keymap = {
            accept_and_goto = "<leader>p",
            accept = false,
            dismiss = "<Esc>",
          },
        },

        filetypes = {
          yaml = true,
          markdown = true,
          help = true,
          gitcommit = false,
          gitrebase = false,
          hgcommit = false,
          svn = false,
          cvs = false,
          ["."] = true,
        },
      })
    end,
  },

  {
    "saghen/blink.cmp",
    optional = true,
    dependencies = { "fang2hou/blink-copilot" },
    opts = {
      sources = {
        default = { "copilot" },
        providers = {
          copilot = {
            name = "copilot",
            module = "blink-copilot",
            score_offset = 100,
            async = true,
          },
        },
      },
    },
  },

  {
    "nvim-pack/nvim-spectre",
    dependencies = { "nvim-lua/plenary.nvim" },
    event = "VeryLazy",
    keys = {
      {
        "<leader>st",
        mode = { "n" },
        function()
          require("spectre").toggle()
        end,
        desc = "Toggle Spectre",
      },
      {
        "<leader>sw",
        mode = { "n", "x" },
        function()
          require("spectre").open_visual({ select_word = true })
        end,
        desc = "Spectre - Replace in files (visual)",
      },
    },
  }
}
